In [2]:
import numpy as np

In [17]:
arr = np.random.randint(1,4, size=(5,5))
arr

array([[2, 2, 2, 3, 2],
       [1, 1, 2, 3, 1],
       [3, 3, 2, 1, 3],
       [1, 2, 2, 2, 1],
       [2, 2, 2, 1, 2]])

In [18]:
# 전치
arr.T # 행과 열이 바뀜
np.transpose(arr)

array([[2, 1, 3, 1, 2],
       [2, 1, 3, 2, 2],
       [2, 2, 2, 2, 2],
       [3, 3, 1, 2, 1],
       [2, 1, 3, 1, 2]])

In [5]:
# 행렬곱, 내적
np.dot(arr.T, arr) # 디테일한것은 선형대수에서

array([[197, 142, 143, 217, 130],
       [142, 146,  92, 181, 139],
       [143,  92, 157, 184, 102],
       [217, 181, 184, 296, 203],
       [130, 139, 102, 203, 162]])

In [9]:
a = np.arange(6).reshape(2,3) # 구조 바꾸는
print(a,'\n')

y = np.swapaxes(a, 0,1) # 0은 2차원(열), 1은 1차원(행) --> 원소의 행과 열을 바꿔
print(y,'\n')             # swapaxes 축을 바꿈

y = a.T
y = np.transpose(a)
y = np.transpose(a)
print(y)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]]


In [ ]:
# 1 ~ 100을 아래와 같이 출력하세요.

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [10]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [3]:
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1: # 홀수이면
        a[i] = a[i][::-1]

print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [14]:
# (0,1,2)  --> 0이 3차원 1이 2차원 2가 1차원
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)

a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))
print(y,y.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3) 



In [16]:
# (1,2,3) -> (2,3,1)  -> 높이1 행2 열3 -> 높이2 행3 열1
# (0,1,2) -> (3차원,2차원,1차원) 

a = np.arange(6).reshape(1,2,3) # 배열의 차원
print(a,a.shape,'\n')
y = np.transpose(a,(1,2,0)) # 전치
print(y,y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [19]:
# [과제] 아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
arr = np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 



In [6]:
import numpy as np

arr = np.arange(16).reshape(2,2,4)

# 행렬의 행과 열을 바꿈
arrt = np.transpose(arr,(1,0,2)) 

print(arr,arr.shape,'\n')
print(arrt,arrt.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [ ]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요(shape 확인)

In [20]:
arr = np.arange(16).reshape(2,2,4) # 3차원 먼저 만듬
print('* 변경 전 :' ,'\n')
print(arr,'\n')

arr21 = np.transpose(arr,(0,2,1)) 
print('* 변경 후 :' ,'\n')
print(arr21,arr21.shape,'\n')

arrs = arr.swapaxes(1,2)
print(arrs,arrs.shape)

* 변경 전 : 

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 

* 변경 후 : 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)


In [21]:
# 나머지를 구할 경우 사용하는 함수 -> mod, remainder

value1 = np.array([15,30,45])
value2 = np.array([2,7,9])

print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [24]:
# 각 수의 역수를 구해주는 함수 -> reciprocal

value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value),'\n')

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1, dtype=float))

[1.17647059 0.54054054 1.         0.01      ] 

[100] 

[0.01]


In [25]:
# 승수의 결과 값을 표시해주는 함수 -> power

value1 = np.array([2,10,15])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

[  4 100 225] 

[   2  100 3375]


In [32]:
arr = np.random.randn(10)
# print(arr.mean(),'\n')
# print(arr.std()) # 표준편차
arr

array([ 0.93844349, -1.70350145,  1.43032172,  1.72771127,  1.18513425,
       -0.17828169, -0.59747204,  1.30479862,  1.80892605,  0.05843872])

In [33]:
# 양수인 원소의 개수
(arr > 0).sum()

7

In [34]:
# 하나 이상의 값이 True인지 검사
bools = np.array([False,False, True,True])
bools.any()

True

In [35]:
# 모든 원소가 True인지 검사
bools.all()

False

In [37]:
# 삼항식의 벡터화 버전 (where 함수랑 같이 씀)

arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2) # np.where(조건 넣어서 사용)

[[ 1.7473973   0.82798397  0.94804643  1.03016619]
 [-0.34239068  0.62847099  0.33205515 -0.22287872]
 [-0.09000575 -0.71853303 -0.93714676  0.91819086]
 [ 1.57169578  1.27593397  0.44396742  0.57010209]] 



array([[ 2,  2,  2,  2],
       [-2,  2,  2, -2],
       [-2, -2, -2,  2],
       [ 2,  2,  2,  2]])

In [38]:
# arr의 모든 양수를 2로 바꿀 경우
np.where(arr > 0, 2, arr) # 양수이면 2로 아니면 원래 배열의 원소로 출력 ** 유용함 자주쓰임

array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [-0.34239068,  2.        ,  2.        , -0.22287872],
       [-0.09000575, -0.71853303, -0.93714676,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

In [40]:
# 두개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열 2개 반환
x = np.arange(1,4)
y = np.arange(1,4)

xs,ys = np.meshgrid(x,y)
print(xs,'\n')
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [47]:
# np.sort() -> 원본 그대로 
np.random.seed(0)
arr = np.random.randint(1,100,size=10)
print(arr,'\n')

print(np.sort(arr),'\n') 
print(arr)

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88] 

[45 48 65 68 68 10 84 22 37 88]


In [48]:
sorted = np.sort(arr) # 변수명(sorted)에 저장해놓고 sort해야 원본이 바뀜
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [51]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,1]])
print(arr2d,'\n')

sort_ar2d_axis0 = np.sort(arr2d, axis=0) # axis=0 행방향 sort
print(sort_ar2d_axis0,'\n')

sort_ar2d_axis1 = np.sort(arr2d, axis=1) # axis=1 열방향 sort
print(sort_ar2d_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [60]:
# ndarray.sort() : 원본 반영  <---> np.sort(arr) 원본 반영 안됨

np.random.seed(0)
arr = np.random.randint(1,10,size=10)
# arr = np.random.randn(6)
print(arr,'\n')

arr.sort() # 원본 반영
print(arr)

[6 1 4 4 8 4 6 3 5 8] 

[1 3 4 4 4 5 6 6 8 8]


In [2]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 열방향 정렬, default
import numpy as np
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')

arr.sort(1) # 열쪽으로 sort 해줌  
print(arr)  # 행쪽이면 ? sort(1)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [66]:
# 행방향 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')

arr.sort(0)
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[4 1 4]
 [6 2 4]
 [6 3 5]
 [8 7 7]
 [9 8 9]]


In [68]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array) # sort한것의 index를 반환
print(org_array) 

print(type(sort_indices))
sort_indices

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [86]:
# 배열에서 정렬한 후 50%에 해당하는 원소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.5*len(large_arr))]

0.05914416657426071

In [87]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [4]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

['Bob', 'Joe', 'Will']

In [5]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [6]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr) # arr배열을 some_array 파일명으로 저장

In [7]:
np.load('some_array.npy') # 가져오기

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr) # 여러개의 배열을 복수로 저장가능 -> 압축가능

In [10]:
arch = np.load('array_archive.npz')
arch['a'] # 특정 배열의 대한 내용 출력

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0] 을 출력하세요.
a = np.ones(10,dtype=int)
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
a = np.ones(10).astype(int)
a[[1,3,5,7,9]] = 0
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [ ]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력

In [12]:
a= np.arange(10)
a1 = a[a>5]
a1

array([6, 7, 8, 9])

In [ ]:
# Q. a에서 최대값 np.argmax() , 최소값 np.argmin() 의 인덱스 출력

In [16]:
a = np.arange(1,10)
print(f'최댓값: {np.argmax(a)}\n최솟값: {np.argmin(a)}')

최댓값: 8
최솟값: 0


In [ ]:
# Q. a에서 인덱스 배열을 역순으로 출력하세요.

In [17]:
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [ ]:
# Q. np.ones((10,10))을 아래와 같이 출력하세요.
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
b=np.ones((10,10))
b[1:9,1:9]=0
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
# [과제] np.ones((5,5))을 아래와 같이 출력하세요.
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])


In [5]:
x = np.ones((5,5), dtype = int)
y = np.zeros((9,9), dtype = int)
y[2:7,2:7] = x # x는 행 2~7 , 열 2~7에 ones 값들
print(y)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [22]:
arr1 = np.ones((5,5))
np.pad(arr1,(2,2),'constant',constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile함수)
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [16]:
a = np.array([[0,1],[1,0]])
b = np.tile(a,(4,4))

print(a,'\n')
print(b,'\n')

[[0 1]
 [1 0]] 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



In [12]:
# numpy.tile 함수는 어레이를 (타일과 같이) 지정한 횟수만큼 반복합니다.
import numpy as np

a = np.array([0, 1, 2])
b = np.tile(a, 2)
c = np.tile(a, (3, 2)) # 0 1 2 배열을 3행 2열로

print(a,'\n')
print(b,'\n')
print(c)
# c.ndim -> 2차

[0 1 2] 

[0 1 2 0 1 2] 

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [14]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.tile(a, 2)
c = np.tile(a, (2, 2))

print(a,'\n')
print(b,'\n')
print(c)

[[1 2]
 [3 4]] 

[[1 2 1 2]
 [3 4 3 4]] 

[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [ ]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [19]:
a = np.arange(336).reshape(6,7,8)
print(np.where(a==99),'\n')

arr = np.arange(336).reshape(6,7,8)
# print(arr)

# numpy.unravel_index( 인덱스 , 모양 , 순서='C' )
# 플랫 인덱스 또는 플랫 인덱스 배열을 튜플 좌표 배열로 변환합니다.
print(np.unravel_index(99,(6,7,8))) 

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64)) 

(1, 5, 3)


In [ ]:
# [도전과제] np.arrange(4)을 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [29]:
arr=np.arange(4) 
# np.diag(arr+1,k=2) 
np.diag(arr+1, k =2) # diag -> 대각행렬 생성

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [24]:
np.diag(1+np.arange(4)) # np.diag(1,2,3,4) 와 같음

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

[파이썬 random 함수]

In [29]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.6368513695008178 

5 

18.9744480022728 

6 

2 

[1, 2, 5] 

[5, 2, 1, 4, 3]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성 -> 난수 고정
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [30]:
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

3 

[1 1 9 3 1 4 7 1 8 9] 

[12 14 16 16 12 14 19 12 15 14] 

[[12 12 18 11 16]
 [19 14 19 13 15]
 [17 19 18 19 16]]


In [32]:
r = np.random.rand(6) # 0 ~ 1 사이의 균일분포
print(r,'\n')
r.mean()

[0.35939011 0.92422949 0.5613698  0.29359141 0.93212749 0.62799602] 



0.6164507206061188

In [61]:
# 표준 정규분포
r = np.random.randn(10000)
print(r,'\n')
r.mean() # 샘플이 많으면 평균이 0으로 분산함

[-0.10321885  0.4105985   0.14404357 ... -1.08502512  0.97226233
  1.43147168] 



-0.01893802539118709

In [37]:
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

[1 2 3 4 5] 



array([3, 1, 4, 2, 5])

In [38]:
np.random.choice(list)

4

In [39]:
a = np.array([11,11,3,3,2,2,2,7])

# 주어진 배열에서 중복된거 제거 후 출력
index,count = np.unique(a,return_counts=True)

print(index) #
print(count) # 2는3개, 3은 2개, 7은1개, 11은 2개

[ 2  3  7 11]
[3 2 1 2]


In [40]:
np.random.uniform(1.0,2.0, 10)

array([1.23196751, 1.41547268, 1.85182497, 1.73567716, 1.33340048,
       1.12387434, 1.49182714, 1.22099167, 1.25233108, 1.42272584])

In [42]:
print(np.random.uniform(0,1,(2,3))) # uniform은 범위지정해줘야함

[[0.7702486  0.27582034 0.94317537]
 [0.34387656 0.00674356 0.48359411]]


In [41]:
# 0 ~ 1 사이의 난수 실수값으로 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0, 1로 지정한 것과 같음
np.random.random_sample((2,3))

array([[0.40762345, 0.86121214, 0.95243613],
       [0.57615261, 0.98855528, 0.58242609]])

In [2]:
!pip install pandas

In [6]:
ar = np.random.rand(4,8) # rand 균일분포 4행 8열
ar

array([[0.75952748, 0.49086493, 0.2882702 , 0.79074203, 0.08961169,
        0.03088171, 0.1350829 , 0.22873948],
       [0.76030927, 0.03281771, 0.91698558, 0.03322285, 0.73179457,
        0.61421108, 0.66757378, 0.85500591],
       [0.60609743, 0.5394213 , 0.84806714, 0.08784687, 0.17888944,
        0.89469666, 0.22178836, 0.78876453],
       [0.30916355, 0.27993381, 0.9870562 , 0.12884018, 0.7113555 ,
        0.06745623, 0.95984212, 0.51553156]])

In [7]:
# 데이터 전처리 하기위해  배열을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
print(df,type(df))

          0         1         2         3         4         5         6  \
0  0.759527  0.490865  0.288270  0.790742  0.089612  0.030882  0.135083   
1  0.760309  0.032818  0.916986  0.033223  0.731795  0.614211  0.667574   
2  0.606097  0.539421  0.848067  0.087847  0.178889  0.894697  0.221788   
3  0.309164  0.279934  0.987056  0.128840  0.711355  0.067456  0.959842   

          7  
0  0.228739  
1  0.855006  
2  0.788765  
3  0.515532   <class 'pandas.core.frame.DataFrame'>


In [49]:
columns = ['id','gender','age','region','product','price','qty','time'] # 칼럼 지정
index = [np.arange(4)] # 인덱스 지정
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.729431  0.684862  0.868469  0.522983  0.030574  0.146772  0.520409   
1  0.544840  0.048985  0.991160  0.719574  0.350430  0.803454  0.833256   
2  0.352445  0.806314  0.018128  0.649153  0.013020  0.929774  0.325772   
3  0.376991  0.381680  0.877992  0.835450  0.742619  0.508451  0.677759   

       time  
0  0.461370  
1  0.383248  
2  0.476830  
3  0.322290

In [ ]:
# Q. id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요.

In [50]:
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data,np.arange(1,4),['ID','Gender','Age'])
df


ID Gender Age
1  6534      M  27
2  1024      F  15
3  6769      M  11

In [51]:
h = np.zeros((3, 10))
id_ = np.random.randint(1, 1000, size = (1, 10))
gender = np.random.randint(2, size = (1, 10))
age = np.random.randint(0, 120, size = (1, 10))

h[0] = id_
h[1] = gender
h[2] = age

h = np.transpose(h)
print(h,'\n')

columns = ['id', 'gender', 'age']
index = np.arange(1, 11)
df = pd.DataFrame(h, index, columns = columns)

df

[[812.   0.  38.]
 [644.   1.  78.]
 [324.   0.  76.]
 [888.   0. 101.]
 [408.   0. 104.]
 [624.   0.  29.]
 [232.   0. 104.]
 [195.   0.  27.]
 [ 30.   1.  12.]
 [511.   1.  45.]] 



id  gender    age
1   812.0     0.0   38.0
2   644.0     1.0   78.0
3   324.0     0.0   76.0
4   888.0     0.0  101.0
5   408.0     0.0  104.0
6   624.0     0.0   29.0
7   232.0     0.0  104.0
8   195.0     0.0   27.0
9    30.0     1.0   12.0
10  511.0     1.0   45.0

In [59]:
ar = np.zeros((4,3)) # 4행 3열짜리 배열 만들어줌
columns = ['id','gender','age'] # 열 정해주고
index = [np.arange(4)] # 행 넣어주고 (4행이니까)
df = pd.DataFrame(ar,index,columns=columns) # 데이터 프레임에 ar, index, colunms을 넣어줌 -> 데이터프레임 완성

# df.id = np.array([1,2,3,4])
df.id = np.arange(1,5) # 데이터프레임.id 에 1~4까지 

# df.gender = np.array([0,1,0,1])
np.random.seed(0) # 변하지 않기 위해 seed

df.gender = np.random.randint(2,size=4) # randint 2 -> 0,1 size 4개
# df.age = np.array([20,30,40,50])

df.age = np.arange(1,5) * 10  # 배열 연산
df

id  gender  age
0   1       0   10
1   2       1   20
2   3       1   30
3   4       0   40

[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요(관측치 1000개)

- id : 1 ~ 1000번 일련번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111 ~ 99999
- product_20 : 제품코드 11111 ~ 99999
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0