In [80]:
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],
                [2,3,4]])
array3 = np.array([[[1,2,3]]])
                
print(array1, type(array1), array1.shape)
print(array2, type(array2), array2.shape)
print(array3, type(array3), array3.shape)         

[1 2 3] <class 'numpy.ndarray'> (3,)
[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)
[[[1 2 3]]] <class 'numpy.ndarray'> (1, 1, 3)


In [81]:
# astype 형변환
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float.dtype)
array_int2 = array_float.astype('int32')
print(array_int2.dtype)

float64
int32


In [11]:
# np.zeros
zero_array = np.zeros((3,2), dtype='int32') 
print(zero_array)
zero_array.ndim # 2차원
zero_array.shape # 3행 2열

[[0 0]
 [0 0]
 [0 0]]


(3, 2)

In [82]:
one_array = np.ones((3,2))
print(one_array, one_array.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64


In [88]:
# reshape ; 1-> 2,3 차원
ar1 = np.arange(10)
print(ar1, ar1.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [89]:
print(ar1,'\n')
print(ar1.reshape(2,5),'\n')
print(ar1.reshape(1,2,5))

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [92]:
# reshape, -1
ar1 = np.arange(10)
print(ar1, ar1.shape)
print(ar1.reshape(2,-1)) # 2행 5열
print(ar1.reshape(-1,5,2)) 

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]


In [101]:
# 3차원 -> 2,1차원
ar3 = np.arange(8).reshape((2,2,2))
print(ar3, ar3.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 3


In [107]:
ar3 = np.arange(8).reshape((2,2,2))
ar2 = ar3.reshape(-1,2) # 2차원
ar1 = ar3.reshape(-1,) # 1차원
print(ar3, ar3.shape)
print(ar2, ar2.shape)
print(ar1, ar1.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]] (4, 2)
[0 1 2 3 4 5 6 7] (8,)


In [110]:
# 1D_indexing
ar1 = np.arange(1,10)
print(ar1)
value = ar1[1]  # 0번째 index부터 시작함 -> 1번째 index
print(value)
print(ar1[-1]) # 마지막번째 인덱스
print(ar1[-3]) # 마지막에서 세번째 인덱스

[1 2 3 4 5 6 7 8 9]
2
9
7


In [112]:
# 2D_indexing 
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d,'\n')
print(ar2d[0,0],'\n')
print(ar2d[0,1],'\n')
print(ar2d[1,0],'\n')
print(ar2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

1 

2 

4 

9


In [125]:
# 1D_slicing 
ar1 = np.arange(1,20)
print(ar1)
print(ar1[3:6])
print(ar1[-4:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6]
[16 17 18]


In [114]:
ar2d = np.arange(1,10).reshape(3,3)
print(ar2d,'\n')
print(ar2d[:2,:2],'\n')
print(ar2d[1:3,:],'\n')
print(ar2d[1:3, 0:3],'\n')
print(ar2d[:2,1:],'\n')
print(ar2d[:2,:1],'\n')
print(ar2d[:2,0]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2]
 [4 5]] 

[[4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]] 

[[1]
 [4]] 

[1 4]


In [131]:
# fancy indexing
ar2 = np.arange(1,10).reshape(3,3)
print(ar2,'\n')
print(ar2[[0,1],2],'\n')
print(ar2[[0,1],:3],'\n')
print(ar2[[0,1]])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[3 6] 

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]]


In [117]:
# boolean indexing
ar1 = np.arange(1,10)
ar2 = ar1[ar1 > 5]
print(ar2)

[6 7 8 9]


In [59]:
# np.sort() -> 원본 미반영
ar = np.array([3,1,9,5])
print(ar)
sort_ar = np.sort(ar)
print(sort_ar)

[3 1 9 5]
[1 3 5 9]


In [69]:
# ndarray.sort() -> 원본 반영
ar = np.array([3,1,9,5])
print(ar)
sort_ar1 = ar.sort()
print(sort_ar1)
print(ar) # 원본이 바뀜

[3 1 9 5]
None
[1 3 5 9]


In [64]:
# 내림차순
sort_ar_desc = np.sort(ar)[::-1]
print(sort_ar_desc)

[9 5 3 1]


In [75]:
ar2 = np.array([[8,12],
               [7,1]])
print(ar2,'\n')

sort_ar2_axis0 = np.sort(ar2, axis=0)
print(sort_ar2_axis0,'\n')

sort_ar2_axis1 = np.sort(ar2, axis=1)
print(sort_ar2_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [79]:
# 정렬 행렬의 인덱스 변환
ar = np.array([3,1,9,5])
print(ar,'\n')

sort_indices = np.argsort(ar)
print(sort_indices)

[3 1 9 5] 

[1 0 3 2]


In [1]:
# 행렬 내적
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[7,8],
             [9,10],
             [11,12]])

In [2]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [3]:
# 전치 행렬
a = np.array([[1,2],
             [3,4]])
# a.T
b = a.transpose()
b

array([[1, 3],
       [2, 4]])