# 판다스
- 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조 (pandas.Series)딕셔너리
- 시리즈는 칼럼이름이 없음, 시리즈가 모여서 데이터프레임의 각 열을 구성
- 하나의 시리즈가 데이터프레임이 될 수 있음

- Contents
    - Series(변환, 인덱스 구조, 원소 선택)
    - DataFrame(변환, 인덱스, 삭제, 선택, 추가, 변경, 전치 등)

In [2]:
# 딕셔너리를 시리즈로 변환
import pandas as pd

dic_data={'a':1, 'b':2 ,'c':3} # key value 형태 -> key가 index  value가 값
sr = pd.Series(dic_data)
print(sr)
print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>


In [3]:
# 리스트를 시리즈로 변환  -> 문자, 숫자, 불린값 사용가능 하지만 key가 없어서 리스트는 값만 잇기에 인덱스를 꼭 넣어줘야함
list_data=['2019-10-02',3.14,'ABC',100,True]
sr=pd.Series(list_data, index=['a','b','c','d','e'])
print(sr,type(sr))

a    2019-10-02
b          3.14
c           ABC
d           100
e          True
dtype: object <class 'pandas.core.series.Series'>


In [4]:
idx=sr.index
print(idx,'\n') # index가 a b c
val=sr.values
print(val) # value가 1 2 3

Index(['a', 'b', 'c', 'd', 'e'], dtype='object') 

['2019-10-02' 3.14 'ABC' 100 True]


In [5]:
# 튜플을 시리즈로 변환 ->  리스트와 마찬가지로 index가 있어야함
tup_data=('영인','2015-05-01','여', True)
sr=pd.Series(tup_data, index=['이름','생년월일','성별','학생여부'])
print(sr,type(sr),'\n')

idxx=sr.index
print(idxx,'\n')
vall=sr.values
print(vall)

이름              영인
생년월일    2015-05-01
성별               여
학생여부          True
dtype: object <class 'pandas.core.series.Series'> 

Index(['이름', '생년월일', '성별', '학생여부'], dtype='object') 

['영인' '2015-05-01' '여' True]


In [40]:
print(sr[0]) # index 0번째의 value 추출
print(sr['이름'],'\n')
print(sr[[1,3]] )# 1index의 value 와 3index의 value 추출

영인
영인 

생년월일    2015-05-01
학생여부          True
dtype: object


In [7]:
# 배열을 시리즈로 변환 -> index가 있어야함

import numpy as np

s1=np.arange(start=11, stop=16) # 11부터 15까지
s2=pd.Series(s1, index=['ED1','ED2','ED3','ED4','ED5']) # s1을 인덱스 부여

print(s1,type(s1),'\n') #배열
print(s2, type(s2)) # 시리즈로 출력

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [8]:
print(s2[1:3],'\n') # index 1 부터 2까지
print(s2[[2,4]]) # index 2 랑 4

ED2    12
ED3    13
dtype: int32 

ED3    13
ED5    15
dtype: int32


In [44]:
# 시리즈 -> 배열

print(type(s2))
ar=np.array(s2) # 시리즈를 배열로 변환
print(ar, type(ar))

<class 'pandas.core.series.Series'>
[11 12 13 14 15] <class 'numpy.ndarray'>


In [49]:
# 4가지 자료형 데이터를 생성하고 각각 Series로 변환하여 출력
# 딕셔너리를 제외하고 index 필요로함 -> 튜플, 리스트, 배열

lidata = [2,3,4,5] # 리스트
tudata = (True,False,True,True) # 튜플
dicdata = {'김첨지':'설렁탕','점순이':'감자','나':'아달린'} # 딕셔너리
arrdata = np.array(['살바도르','빈센트','파블로','램브란트']) # 배열
index = ['1번','2번','3번','4번'] # 인덱스 why? -> 딕셔너리 빼고 다 필요하기에

li=pd.Series(lidata, index)
tu=pd.Series(tudata, index)
dic=pd.Series(dicdata) # 딕셔너리는 index가 없어도됨
arr=pd.Series(arrdata, index)

print(li,'\n','\n',tu)
print('\n', dic,'\n')
print(arr)

1번    2
2번    3
3번    4
4번    5
dtype: int64 
 
 1번     True
2번    False
3번     True
4번     True
dtype: bool

 김첨지    설렁탕
점순이     감자
나      아달린
dtype: object 

1번    살바도르
2번     빈센트
3번     파블로
4번    램브란트
dtype: object


In [9]:
data= np.arange(1000,5000,1000)
obj=pd.Series(data)
state=['Califonia','Ohio','Oregon','Texas']
obj.name= 'population'
obj.index=state
obj.index.name='state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [10]:
obj.Califonia=np.nan # 인덱싱
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [11]:
obj['Newyork']=3000 # 값 추가

In [13]:
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Newyork      3000.0
Name: population, dtype: float64

In [14]:
obj.isnull() # 널값 확인

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Newyork      False
Name: population, dtype: bool

# 데이터프레임
- 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래
- 데이터프레임의 열은 각각 시리즈 개체
- 시리즈를 열벡터하고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬
- 선형대수학에서 열 벡터(mx1행렬)는 m원소들의 단일 열 행렬
- 행 벡터(1xm행렬)은 m원소들의 단일 행 행렬
- 리스트, 딕셔너리,배열 등 다양한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, 배열 등으로 변환될 수 있음

In [16]:
# 배열 -> 데이터프레임
import numpy as np
ar=np.random.randint(100,120, size=(3,3)) #100~119 3*3 행렬 생성
print(ar,type(ar),'\n') # 2차원 배열 , type 출력

df=pd.DataFrame(ar, index=['d1','d2','d3'], # 배열 ar에 인덱스 주고 컬럼주고 -> 만약 인덱스 안주면 자동 할당 0 1 2 ..
                columns=['pd','sales','int']) # columns도 설정안하면 자동 할당 0 1 2 ..
print(df,type(df))

[[106 105 116]
 [101 117 114]
 [100 104 107]] <class 'numpy.ndarray'> 

     0    1    2
0  106  105  116
1  101  117  114
2  100  104  107 <class 'pandas.core.frame.DataFrame'>


##### pandas indexing
- iloc : integer location의 약어, 데이터프레임의 행이나 칼럼의 순서를 나타내는 정수로 특정 값을 추출해오는 방법
- loc : 인덱스명, 칼럼명을 직접 적거나 특정 조건식을 써줌으로써 사람이 읽기 좋은 방법으로 데이터에 접근하는 방법

In [4]:
# 행 선택
print(df,'\n')
print(df.iloc[1],'\n') # index 첫번째 행 선택 #정수로 선택
print(df.loc['d2'])  # 인덱스명, 칼럼명을 직접 적거나 조건식 써줌

     pd  sales  int
d1  112    107  116
d2  112    115  102
d3  105    105  103 

pd       112
sales    115
int      102
Name: d2, dtype: int32 

pd       112
sales    115
int      102
Name: d2, dtype: int32


In [5]:
# 특정 행, 열 선택
print(df.iloc[1,1],'\n')
print(df.loc['d2','sales']) # 인덱스명, 칼럼명으로 직접 적거나 조건식 씀

115 

115


In [6]:
# 행, 열 추가
df1=df.copy() # 복사
df1.loc['d5']=0  # d5 행 모두 0으로
df1

pd  sales  int
d1  112    107  116
d2  112    115  102
d3  105    105  103
d5    0      0    0

In [7]:
# 새로운 열을 생성시 유의
import pandas as pd
df1['pf']=[100,100,100,0]
df1

pd  sales  int   pf
d1  112    107  116  100
d2  112    115  102  100
d3  105    105  103  100
d5    0      0    0    0

In [30]:
print(type(df1.pf))
df1.pf

<class 'pandas.core.series.Series'>


d1    100
d2    100
d3    100
d5      0
Name: pf, dtype: int64

In [31]:
#원소 값 변경
df1.iloc[1,1]=np.nan
df1

pd  sales  int   pf
d1  109  110.0  100  100
d2  116    NaN  106  100
d3  114  100.0  106  100
d5    0    0.0    0    0

In [39]:
# 사전-> 데이터프레임으로 : key값이 컬럼명이 됨(칼럼명 안줘도됨)
sp1=np.arange(1,6)
df=pd.DataFrame({
    'col1':sp1, # col1 에는 sp1 배열값 1~5까지 넣기
    'col2':sp1 * 2, # c0l2에는 배열값 *2
    'col3':['A','B','C','D','E'] # col3에는 직접 값 추가
})

df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [44]:
# 딕셔너리에서 값이 스칼라이면 인덱스 필요

dic={'A':1,'B':2,'C':3,'D':4}
# dic={'A':[1],'B':[2],'C':[3],'D':[4]}

columns=['a','b','c','d','e']
index=[1,2,3,4]

df_dic=pd.DataFrame(dic,index)
# df_dic=pd.DataFrame(dic)

print(df_dic)

   A  B  C  D
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4
4  1  2  3  4


In [50]:
# 리스트 -> 데이터프레임(칼럼명 별도로 설정)

a=np.random.randint(1,5, size=(10,5)) #배열생성
#print(type(a))  type프린트 해보면 ndarray ->배열

list1=a.tolist() # 배열형태를 리스트로 convert
list1

index =np.arange(1,11) # 리스트를 다시 데이터프레임으로
df=pd.DataFrame(list1, index, columns =['c1','c2','c3','c4','c5'])
df   

c1  c2  c3  c4  c5
1    2   4   1   3   2
2    4   2   3   1   2
3    3   2   4   3   2
4    2   2   2   4   2
5    1   1   2   3   3
6    2   1   2   1   3
7    1   4   1   4   2
8    1   3   1   2   4
9    1   2   4   1   4
10   2   3   4   1   3

In [56]:
# 데이터프레임 -> 배열, 리스트, 딕셔너리

ar =df.values  # 데이터프레임.values -> 배열로 전환
print(ar, type(ar),'\n')

li=df.values.tolist() # 리스트로 convert df.values.tolist()
print(li,type(li),'\n') # 직접 바꾸진 않고 배열로 바꾼다음 리스트로 바꿈

dict=df.to_dict('list') # 딕셔너리 -> 딕셔너리의 key,value 중 key가 list이므로
print(dict,type(dict))

[[2 4 1 3 2]
 [4 2 3 1 2]
 [3 2 4 3 2]
 [2 2 2 4 2]
 [1 1 2 3 3]
 [2 1 2 1 3]
 [1 4 1 4 2]
 [1 3 1 2 4]
 [1 2 4 1 4]
 [2 3 4 1 3]] <class 'numpy.ndarray'> 

[[2, 4, 1, 3, 2], [4, 2, 3, 1, 2], [3, 2, 4, 3, 2], [2, 2, 2, 4, 2], [1, 1, 2, 3, 3], [2, 1, 2, 1, 3], [1, 4, 1, 4, 2], [1, 3, 1, 2, 4], [1, 2, 4, 1, 4], [2, 3, 4, 1, 3]] <class 'list'> 

{'c1': [2, 4, 3, 2, 1, 2, 1, 1, 1, 2], 'c2': [4, 2, 2, 2, 1, 1, 4, 3, 2, 3], 'c3': [1, 3, 4, 2, 2, 2, 1, 1, 4, 4], 'c4': [3, 1, 3, 4, 3, 1, 4, 2, 1, 1], 'c5': [2, 2, 2, 2, 3, 3, 2, 4, 4, 3]} <class 'dict'>


In [90]:
# 배열, 리스트, 딕셔너리로 데이터프레임을 생성한 후 다시 배열, 리스트, 딕셔너리로 변환하여 출력 
# index는 따로 설정안해주면 0부터 시작

ar=np.arange(1,5) # value 값을 1~5까지 무작위로 뿌려보림
ar2=ar*2 # 배열 a1에 2 곱하기

li=ar.tolist() # 배열 리스트로 변환
df=pd.DataFrame({
    'col1': ar,
    'col2': li,
    'col3':np.nan
})

print(df,type(df),'\n') # 데이터프레임
print(df.values, type(df.values),'\n') # df.values는  배열임
print(df.values.tolist(),type(df.values.tolist()),'\n')# df.values.tolist 하면 리스트로 됨
print(df.to_dict('list'),type(df.to_dict('list')), '\n') # df.to_dict 하면 리스트로


   col1  col2  col3
0     1     1   NaN
1     2     2   NaN
2     3     3   NaN
3     4     4   NaN <class 'pandas.core.frame.DataFrame'> 

[[ 1.  1. nan]
 [ 2.  2. nan]
 [ 3.  3. nan]
 [ 4.  4. nan]] <class 'numpy.ndarray'> 

[[1.0, 1.0, nan], [2.0, 2.0, nan], [3.0, 3.0, nan], [4.0, 4.0, nan]] <class 'list'> 

{'col1': [1, 2, 3, 4], 'col2': [1, 2, 3, 4], 'col3': [nan, nan, nan, nan]} <class 'dict'> 



In [79]:
# 리스트
li =['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'], columns=['차림표'])
print(df1,'\n')

# 데이터프레임을 리스트로 convert
print(df1.values.tolist(), type(df1.values.tolist()),'\n')

# 딕셔너리
df2= pd.DataFrame({
    '커피':4000,
    '쿠키':3000,
    '케이크':6500
}, index=['가격'])

print(df2,'\n')
print(df2.to_dict('list'), type(df2.to_dict('list')), '\n')

# 배열 
df3=pd.DataFrame(np.random.randint(1,10,size=(3,3)),index=['1반','2반','3반'],
                 columns=['달리기','줄다리기','무궁화'])
print(df3,'\n')
print(df3.values)

      차림표
메뉴1    냉면
메뉴2   칼국수
메뉴3  잔치국수
메뉴4   수제비
메뉴5    우동 

[['냉면'], ['칼국수'], ['잔치국수'], ['수제비'], ['우동']] <class 'list'> 

      커피    쿠키   케이크
가격  4000  3000  6500 

{'커피': [4000], '쿠키': [3000], '케이크': [6500]} <class 'dict'> 

    달리기  줄다리기  무궁화
1반    1     3    2
2반    4     6    9
3반    8     2    1 

[[1 3 2]
 [4 6 9]
 [8 2 1]]


In [17]:
# file 생성, 저장, 읽기

import pandas as pd
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2', '메뉴3','메뉴4','메뉴5'],columns=['차림표'])
print(df1)

df1.to_csv('./dataset/file_data.csv') 
file_data = pd.read_csv('./dataset/file_data.csv')
# file_data = pd.read_csv('./dataset/file_data.csv',index_col=0) # 읽기
file_data

# 하나의 열 형태로 데이터프레임을 생성 할 수 있다  columns 해서 칼럼명을 주면 가능

      차림표
메뉴1    냉면
메뉴2   칼국수
메뉴3  잔치국수
메뉴4   수제비
메뉴5    우동


Unnamed: 0   차림표
0        메뉴1    냉면
1        메뉴2   칼국수
2        메뉴3  잔치국수
3        메뉴4   수제비
4        메뉴5    우동

In [15]:
df1.to_csv('./dataset/file_data.csv', index=None) 
file_data = pd.read_csv('./dataset/file_data.csv')
file_data

차림표
0    냉면
1   칼국수
2  잔치국수
3   수제비
4    우동

In [19]:
file_data = pd.read_csv('./dataset/file_data.csv',index_col=0) # 0컬럼에 해당하는것을 index로 지정함
file_data

차림표
메뉴1    냉면
메뉴2   칼국수
메뉴3  잔치국수
메뉴4   수제비
메뉴5    우동

### 딕셔너리로 데이터프레임을 만들면 데이터프레임의 열(column)을 하나씩 세워가는 형태 (axis=1) 리스트로 만들면 행(row) 하나씩 아래로 적층 형태 (default, axis=0)
 - 딕셔너리 형태
    - dict_data={'c0':[1,2,3], 'c1':[4,5,6], ... 'c4':[13,14,15]

In [1]:
import pandas as pd

dict_data={'c0':[1,2,3],'c1':[4,5,6], 'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
df=pd.DataFrame(dict_data)
df 

c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
# 리스트는 행 (가로 형태로 적재)
df=pd.DataFrame([[14,'남','엄경중'],[17,'여','양동중'],[18,'남','노무중']],
               index =['준서','예은','무현'],
               columns =['나이','성별','학교'])
df

나이 성별   학교
준서  14  남  엄경중
예은  17  여  양동중
무현  18  남  노무중